FROM ubuntu:22.04 AS dpkg-build
RUN apt-get update -qq \
    && apt-get install -y \
        build-essential debhelper  \
        virtualenv dh-virtualenv \
        python3 python3-setuptools python3-pip python3-dev \
        dh-exec dh-python \
        gcc libpq-dev libmariadb3 libmariadb-dev python3-distutils freetds-dev libodbc2\
    && apt-get clean && rm -rf "/var/lib/apt/lists"/*
WORKDIR /dpkg-build
